dataloading:
  batch_size: 5
  num_workers: 4
  shuffle: True
  data_path: '../showcase_input_data/plantsegmentation'
  resize_size: [512, 512]

model:
  path_to_model: 'Contact us for pretrained models'
  num_classes: 2
  encoder: 'efficientnet-b7'
  encoder_weights: 'advprop'

datasaving:
  output_folder: '../showcase_output_data/plantsegmentation'
