dataloading:
  batch_size: 5
  num_workers: 4
  shuffle: False
  resize_size: [224, 224]
  data_path_image: '/Users/janzdrazil/Desktop/new_age_image/PLANTAIGIT/showcase_input_data/planteval/plantevalimages'
  data_path_csv: '/Users/janzdrazil/Desktop/new_age_image/PLANTAIGIT/showcase_input_data/planteval/labels.csv'

model:
  path_to_model: '/Users/janzdrazil/Desktop/new_age_image/PLANTAIGIT/trained_models/EVALmodel.pt'
  num_outputs: 24
  model_name: 'ghostnetv2_160.in1k'
  pretrained: True


