dataloading:
  batch_size: 5
  num_workers: 4
  shuffle: False
  resize_size: [224, 224]
  data_path_image: '../showcase_input_data/planteval/plantevalimages'
  data_path_csv: '../showcase_input_data/planteval/labels.csv'

model:
  path_to_model: 'Contact us for pretrained models'
  num_outputs: 24
  model_name: 'ghostnetv2_160.in1k'
  pretrained: True


